spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://memory-rds.cxb5ayqjhhe1.ap-northeast-2.rds.amazonaws.com:3306/memory?autoReconnect=true
    username: root
    password: babymemoryrds
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true